FROM node:20-bookworm-slim AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npm run build:esbuild
RUN mkdir -p /app/nginx-html && cp -r /app/dist-esbuild/browser/. /app/nginx-html/

FROM nginx:alpine

COPY .docker/nginx.conf /etc/nginx/conf.d/default.conf

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /app/nginx-html /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
