services:
  app-esbuild:
    image: arcgis-build:prod
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod-esbuild
    ports:
      - '8080:80'

  app-webpack:
    image: arcgis-build:prod-webpack
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod-webpack
    ports:
      - '8081:80'
